### ISSUE TITLE
AVL tree?

### ISSUE THREAD

**Issue by jeffhammond** [jeffhammond/old-armci-mpi#25]
AVL tree will be faster than linked-list traversal for GMR lookup.

https://github.com/freebsd/freebsd/blob/master/sys/cddl/contrib/opensolaris/common/avl/avl.c exists but I do not know if CDDL is acceptable in ARMCI-MPI.  If not, we'll have to implement from scratch.

**Comment by jdinan** [comment]
Fortunately, ARMCI-MPI already has an AVL tree: https://github.com/jeffhammond/armci-mpi/blob/master/src/conflict_tree.c

Not sure why I didn't use this for GMR lookups.  I suspect the reason is that when the number of memory regions is small, the performance improvement is negligible.

**Comment by jeffhammond** [comment]
Why didn’t you name it “AVL tree” then? 😜

**Comment by jeffhammond** [comment]
Migrated to https://github.com/pmodels/armci-mpi/issues/18
